const weatherMap = {
  '0': 'Cerah',
  '1': 'Cerah Berawan',
  '2': 'Cerah Berawan',
  '3': 'Berawan',
  '4': 'Berawan Tebal',
  '5': 'Udara Kabur',
  '10': 'Asap',
  '45': 'Kabut',
  '60': 'Hujan Ringan',
  '61': 'Hujan Sedang',
  '63': 'Hujan Lebat',
  '80': 'Hujan Lokal',
  '95': 'Hujan Petir',
  '97': 'Hujan Petir'
};

const regionList = [
  'DKI Jakarta',
  'Aceh',
  'Bali',
  'Bangka Belitung',
  'Banten',
  'Bengkulu',
  'DI Yogyakarta',
  'Gorontalo',
  'Jambi',
  'Jawa Barat',
  'Jawa Tengah',
  'Jawa Timur',
  'Kalimantan Barat',
  'Kalimantan Selatan',
  'Kalimantan Tengah',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Kepulauan Riau',
  'Lampung',
  'Maluku',
  'Maluku Utara',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Papua',
  'Papua Barat',
  'Riau',
  'Sulawesi Barat',
  'Sulawesi Selatan',
  'Sulawesi Utara',
  'Sumatera Barat',
  'Sumatera Selatan',
  'Sumatera Utara',
];
